DROP TABLE IF EXISTS prices;
DROP TABLE IF EXISTS brand;
DROP TABLE IF EXISTS product;

CREATE TABLE brand
(
    brand_id         INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    creation_date    TIMESTAMP                            NOT NULL,
    creation_user    VARCHAR(30)                          NOT NULL,
    last_update_date TIMESTAMP,
    last_update_user VARCHAR(30),
    brand_name       VARCHAR(255),
    CONSTRAINT pk_brand PRIMARY KEY (brand_id)
);

CREATE TABLE prices
(
    price_list       INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    creation_date    TIMESTAMP                            NOT NULL,
    creation_user    VARCHAR(30)                          NOT NULL,
    last_update_date TIMESTAMP,
    last_update_user VARCHAR(30),
    brand_id         BIGINT                               NOT NULL,
    start_data       TIMESTAMP                            NOT NULL,
    end_date         TIMESTAMP                            NOT NULL,
    product_id       BIGINT                               NOT NULL,
    priority         INT                                  NOT NULL,
    price            DECIMAL                              NOT NULL,
    currency         VARCHAR(255),
    CONSTRAINT pk_prices PRIMARY KEY (price_list)
);

CREATE TABLE product
(
    product_id       INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    creation_date    TIMESTAMP                            NOT NULL,
    creation_user    VARCHAR(30)                          NOT NULL,
    last_update_date TIMESTAMP,
    last_update_user VARCHAR(30),
    product_name     VARCHAR(255),
    CONSTRAINT pk_product PRIMARY KEY (product_id)
);

ALTER TABLE prices
    ADD CONSTRAINT FK_BRAND_ID FOREIGN KEY (brand_id) REFERENCES brand (brand_id);

ALTER TABLE prices
    ADD CONSTRAINT FK_PRODUCT_ID FOREIGN KEY (product_id) REFERENCES product (product_id);
